import { PrismaClient } from '@prisma/client'
import { ApifyClient } from 'apify-client'
import 'dotenv/config'

const prisma = new PrismaClient()

// Initialize the Apify Client. The APIFY_TOKEN would be stored in your .env file
const apifyClient = new ApifyClient({
    token: process.env.APIFY_TOKEN || 'MOCK_TOKEN',
})

async function syncDispensaries() {
    console.log("🚀 Starting Weedmaps Data Synchronization Pipeline...");

    let results: any[] = [];

    // In production, we run a pre-built Weedmaps Scraper Actor on Apify.
    // This bypasses Cloudflare/Bot protection and returns pure JSON for a target geo-location.
    if (process.env.APIFY_TOKEN) {
        console.log("⚡ Connecting to Apify to run Weedmaps scraper task...");

        // Replace with the actual Actor ID from Apify (e.g. weedmaps-scraper)
        const run = await apifyClient.actor("actor_id_here").call({
            // Input parameters for the scraper
            "location": "Michigan",
            "limit": 50, // Test run limit
        });

        // Fetch the parsed JSON results from the Dataset
        console.log("📥 Fetching dataset from Apify run...");
        const dataset = await apifyClient.dataset(run.defaultDatasetId).listItems();
        results = dataset.items;
    } else {
        console.log("⚠️ No APIFY_TOKEN found. Simulating data payload returned by the Apify Weedmaps Scraper...");
        // Mocking the Apify return payload structure for demonstration
        results = [
            {
                id: "wm-12345",
                name: "Lume Cannabis Co.",
                license_number: "AU-R-000185", // The critical 2026 data point
                address: "508 W College Ave, Ann Arbor, MI 48103",
                latitude: 42.279,
                longitude: -83.743,
                updated_at: new Date().toISOString(),
                menu_items_count: 420
            },
            {
                id: "wm-67890",
                name: "Information Entropy",
                license_number: "AU-R-000216",
                address: "1115 Broadway St, Ann Arbor, MI 48105",
                latitude: 42.289,
                longitude: -83.738,
                updated_at: new Date().toISOString(),
                menu_items_count: 510
            }
        ];
    }

    console.log(`\n🔍 Processing ${results.length} dispensaries for Upsert to Database...`);

    // Loop through extracted Apify objects and safely merge them into PostgreSQL (SQLite for local)
    for (const item of results) {
        try {
            // Upsert: Create if it doesn't exist, UPDATE if it does (keeps menus fresh)
            const dispensary = await prisma.dispensary.upsert({
                where: {
                    // Assuming an external unique identifier is added to Schema (e.g. weedmapsId).
                    // For now, let's use name to simulate the upsert, but in production use a custom unique key.
                    id: item.id // If we mapped our Schema IDs to external IDs, normally you'd use a unique `externalId` field.
                },
                update: {
                    lastMenuUpdateAt: item.updated_at,
                    verified: true,
                    // You would also sync menu/inventory changes here
                },
                create: {
                    id: item.id, // Or let Prisma autogenerate CUID and store external_id separately
                    name: item.name,
                    licenseNumber: item.license_number,
                    address: item.address,
                    latitude: item.latitude,
                    longitude: item.longitude,
                    verified: true, // We trust Weedmaps data freshness
                    lastMenuUpdateAt: item.updated_at
                }
            });

            console.log(`✅ Synced: ${dispensary.name} (Lic: ${dispensary.licenseNumber})`);

        } catch (e: any) {
            // Since 'id' is generated by cuid default, we will catch the mock insert issue and do a first-or-create pattern instead
            const existing = await prisma.dispensary.findFirst({
                where: { name: item.name }
            });

            if (existing) {
                await prisma.dispensary.update({
                    where: { id: existing.id },
                    data: { lastMenuUpdateAt: new Date(item.updated_at), verified: true }
                });
                console.log(`🔄 Updated existing: ${item.name}`);
            } else {
                await prisma.dispensary.create({
                    data: {
                        name: item.name,
                        licenseNumber: item.license_number,
                        address: item.address,
                        latitude: item.latitude,
                        longitude: item.longitude,
                        verified: true,
                        lastMenuUpdateAt: new Date(item.updated_at)
                    }
                });
                console.log(`✨ Created new: ${item.name}`);
            }
        }
    }

    console.log("\n🏁 Synchronization Pipeline Complete. Directory is updated.");
}

syncDispensaries()
    .catch(e => {
        console.error("❌ Pipeline Failed:", e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
